### ISSUE TITLE
resend / verify of sent e_invoices

### ISSUE THREAD

**Issue by teadur** [internetee/e_invoice#2]
Currently if there are problems accessing omniva ( for example network connectivity issues ) 
e_invoices made in the problematic timeframe are never sent to omniva.

We should be able to resend missing invoices.

**Comment by yulgolem** [comment]
Since e-invoice gem uses does not support data storage, decided to resolve this on the registry side.

**Comment by vohmar** [comment]
for registry solved by https://github.com/internetee/registry/issues/1509
remains to be seen how to handle this on auction side once e-invoices are implemented
