### ISSUE TITLE
E-invoices are not forwarded by omniva

### ISSUE THREAD

**Issue by vohmar** [internetee/e_invoice#3]
apparently the invoice must also have following element for Ominva to try to forward it to the client:

\<information content>SENT</information content>

**Comment by vohmar** [comment]
spec for omniva e-invoice api: 
[eArvekeskus_Integration_Specification_v4.3 (1).pdf](https://github.com/internetee/e_invoice/files/3879044/eArvekeskus_Integration_Specification_v4.3.1.pdf)

**Comment by yulgolem** [comment]
Suppose the correct tag is
`<Extension extensionId="eakStatusAfterImport">
   <InformationContent> status after import </InformationContent>
</Extension>`
