### ISSUE TITLE
Invoices are missing payment reference id

### ISSUE THREAD

**Issue by vohmar** [internetee/e_invoice#6]
XML currently has only payment reference number that apparently is not enough to send an e-invoice directly to the bank.

To fix we need to send „PaymentReferenceNumber“ and „PaymentRefId“ and fill both with reference number as value.

also ServiceID is needed again filled with the reference nr

**Comment by artur-beljajev** [comment]
Why `PaymentReferenceNumber` should be provided in addition to `PaymentRefId`? (which is already present).

**Comment by vohmar** [comment]
To enable sendind e-invoices directly to bank. It fails currently because of this.

**Comment by artur-beljajev** [comment]
Fails because we only send `PaymentRefId`, not both of above mentioned?

**Comment by vohmar** [comment]
We currently send PaymentRefId filled with registrars reference number, Upon attempt to send and invoice to registrars bank we get an error  "Invalid or incorrect ServiceID (does not correspond to the Seller's agreement)." Omniva replied to my query that we should add „PaymentReferenceNumber“ and „PaymentRefId“ filled with reference number as value. So it indeed seems that we need to send both to fix this.

**Comment by vohmar** [comment]
apparently in addition to paymentreferencenumber, paymentrefid we also need serviceId. All filled with registrars reference number. Updated ticket description as well.

**Comment by vohmar** [comment]
closed by https://github.com/internetee/e_invoice/pull/7
